spring:
  application:
    name: Bank-ms
  batch:
    job:
      enabled: true
  profiles:
    active: default
  cloud:
    config:
      uri: "${CONFIG_SERVER_URI:http://localhost:8888}"  # Using environment variable or default value
      fail-fast: true
#      label: feat/ai-10-set-up-the-server-config